### ISSUE TITLE
No Module name 'perceiver_ar'

### ISSUE THREAD

**Issue by faisalriazz** [google-research/perceiver-ar#24]
I am following your repo to reproduce code in Google Colab but receiving this error even on Local system. 
# Local system
![image](https://user-images.githubusercontent.com/46712242/209985674-c8a06f7d-68d3-470b-9d9b-a908aabe4ec8.png)
# Google  Colab
![image](https://user-images.githubusercontent.com/46712242/209985771-35f46535-109b-4cd4-9c88-93f7c5bfa6d7.png)

**Comment by cghawthorne** [comment]
I suspect your issue is that the `perceiver_ar` directory is not in your Python module search path. You can see in the example commands I have `PYTHONPATH=.::$PYTHONPATH` at the beginning of each command to add the current directory. It looks like you're using Windows, so the command may be something a little different.
